### ISSUE TITLE
Expand the usage of testClassName#testMethodName for all the API 

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/test-runner#101]
In https://github.com/STAMP-project/test-runner/pull/100, the API is expecting test method names in the following format : `testClassName#testMethodName` for `CoveredTestResultsPerTestMethod`.

This usage should be expanded to all the other APIs :

- [ ] TestResult
- [ ] Coverage
- [ ] CoveragePerTestMethod

**Comment by andre15silva** [comment]
The main issue I see is that the output will be different to what is expected because of the changes in the names of test methods. Maybe if we introduce an option, where the default would be simple name?

**Comment by danglotb** [comment]
Do you mean that we would use an option in order to specify one format or the other, in order to be retro-compatible?

I would say that we break the API (and old projects using the old versions of `test-runner`) and release a new major version of `test-runner`. I don't really see the point of having such an option (unless for retro-compatibility). This option will be drag forever without real meaning, isn't?

My point of view is that have the `testClassName#testMethodName` is richer than only the simple test method names and thus it would be better for all the users. One day, we must take the step and I think it is better to do it ASAP.

WDYT?

**Comment by andre15silva** [comment]
> Do you mean that we would use an option in order to specify one format or the other, in order to be retro-compatible?

Yes.
 
> I would say that we break the API (and old projects using the old versions of `test-runner`) and release a new major version of `test-runner`. I don't really see the point of having such an option (unless for retro-compatibility). This option will be drag forever without real meaning, isn't it?
>
> My point of view is that have the `testClassName#testMethodName` is richer than only the simple test method names and thus it would be better for all the users. One day, we must take the step and I think it is better to do it ASAP.
>
> WDYT?

If you think it is worth it, then I follow you. I definitely agree that it is a richer output.

I'll prepare a PR for this issue and the new major release.
