### ISSUE TITLE
Support multiple classes directories

### ISSUE THREAD

**Issue by andre15silva** [STAMP-project/test-runner#103]
Right now, test-runner assumes only two directories are passed in the `targetProjectClasses`, with the first one being the source classes dir, and the second the test classes dir.

https://github.com/STAMP-project/test-runner/blob/90d7a84f119a865f6d232de49ddd8dfe0f5f7289/src/main/java/eu/stamp_project/testrunner/runner/coverage/JUnit4JacocoRunnerCoveredResultPerTestMethod.java#L45-L47

We should also support several classes directories, possibly through a different API which separates source and test classes in the arguments.

**Comment by danglotb** [comment]
Hi @andre15silva,

Is there any real use case for this? I do not see why one would like to have multiple `classes` and `test-classes` directories.

**Comment by andre15silva** [comment]
Hi @danglotb ,

https://github.com/SpoonLabs/astor supports several directories for both application and test binaries. That is why I want to add this feature, so that flacoco can be integrated in astor without any issue coming up.

I do agree that this is probably a very rare case, but supporting I'd argue that supporting it doesn't impact anything else.

**Comment by tdurieux** [comment]
> Hi @andre15silva,
> 
> Is there any real use case for this? I do not see why one would like to have multiple `classes` and `test-classes` directories.

It is the case in multi-module projects.
