### ISSUE TITLE
set up continuous delivery in Github Actions

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/test-runner#132]
Each commit should be deployed as stable on Maven Central. Each commit increases the patch number

3.1.5 -> commit -> 3.1.6

Then it's easy for clients to stay up to date, in particular flacoco

Reference: we do this for https://github.com/SpoonLabs/gumtree-spoon-ast-diff/

Any volunteer to make this happen?

**Comment by danglotb** [comment]
Hello,

Currently, we deploy a SNAPSHOT on maven central at each commit: see [mvn-deploy-action.yml](https://github.com/STAMP-project/test-runner/blob/master/.github/workflows/mvn-deploy-action.yml).

Should we replace this chore with another to make a stable release at each commit? If so, we will lose control over the [releases on GitHub](https://github.com/STAMP-project/test-runner/releases).

**Comment by danglotb** [comment]
First attemps #133

**Comment by monperrus** [comment]
does it work?

**Comment by monperrus** [comment]
:+1:

**Comment by monperrus** [comment]
Looking at the badge, we are now at version 4.4 :)

https://search.maven.org/artifact/eu.stamp-project/test-runner/

that's cool!

but expected?

**Comment by danglotb** [comment]
Actually, no. 

The automatization has been out of control.

The new version number has been built from 3.1.3 and not from 4.0 hence, the 4.4.

I think that I went too fast between the commits.

However, it should be now stable. The next commit should release 4.5.

**Comment by monperrus** [comment]
ack. let's do a documentation commit to try?

**Comment by danglotb** [comment]
I added a new option and the new version of test-runner is [`4.6`](https://search.maven.org/artifact/eu.stamp-project/test-runner/4.6/jar).

it seems to work properly.

**Comment by monperrus** [comment]
great!
