### ISSUE TITLE
Fix: Continuous Delivery

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/test-runner#153]

**Comment by danglotb** [comment]
[`eu.stamp-project.test-runner-4.14`](https://oss.sonatype.org/#nexus-search;gav~eu.stamp-project~test-runner~~~~kw,versionexpand) has been deployed.
![image](https://github.com/user-attachments/assets/6e002084-8b23-4e19-bdcf-3aea1c36ec1a)


Continuous Delivery should be up and running. Happy testing! :beer: 

Weirdly, it does not have the suffix `-SNAPSHOT`.

**Comment by monperrus** [comment]
thanks a lot @danglotb !
