### ISSUE TITLE
Several test clases in the same execution

### ISSUE THREAD

**Issue by martinezmatias** [STAMP-project/test-runner#86]
The current version  receives as input one test class name and, optionally, a test name.
We would like to send as input several test classes.

**Comment by andre15silva** [comment]
There are API endpoints for this, but if there are test methods with the same name in different test classes it is not able to store the information, as the keys are just the test method names with no information about the test class they belong to.

**Comment by andre15silva** [comment]
Ideally, it should support test method names in the format `"junit5.TestSuiteExample#test3", "junit5.TestSuiteExample2#test3"`
