### ISSUE TITLE
Deploy 2.3.0

### ISSUE THREAD

**Issue by andre15silva** [STAMP-project/test-runner#90]
Would it be possible to deploy release `2.3.0`?

Currently https://github.com/SpoonLabs/flacoco uses the latest SNAPSHOT. Would it be possible to deploy `2.3.0` so that we can get CI running there?

**Comment by danglotb** [comment]
Hi @andre15silva 

I'm gonna try to release test-runner ASAP.

**Comment by andre15silva** [comment]
Thank you @danglotb !

**Comment by danglotb** [comment]
Right now, the tests do not pass locally. I opened #91 to fix this. I proceed to the release as soon as this PR is merged.

**Comment by danglotb** [comment]
Idk what happened to Travis, I'm not able to trigger a build... I might need to go to GitHub actions.

@monperrus Do you have advice about this? Should we move the CI of `test-runner` to GitHub actions? Or any other platform? I was trying to do so for DSpot, but It seems to not to be straightforward as I thought.

Thank you

**Comment by andre15silva** [comment]
Travis moved to `travis-ci.com`. Are you trying there or in `travis-ci.org`?

**Comment by danglotb** [comment]
Both actually, I cannot find the project either in travis-ci.com or travis-ci.org.

**Comment by danglotb** [comment]
`test-runner-2.3.0` has been released. I'll make it available on GitHub and should be on maven central very soon.

**Comment by danglotb** [comment]
Here you go: https://search.maven.org/artifact/eu.stamp-project/test-runner/2.3.0/jar

**Comment by monperrus** [comment]
> Should we move the CI of test-runner to GitHub actions?

Yes, that would be great!

**Comment by andre15silva** [comment]
Thank you @danglotb !

**Comment by danglotb** [comment]
FYI: I setup Github Actions for CI and deployment of test-runner SNAPSHOTs on [Nexus](https://oss.sonatype.org/#nexus-search;gav~eu.stamp-project~test-runner~~~~kw,versionexpand) at each new commit on the master.

Happy hacking @andre15silva !
